### ISSUE TITLE
Scale parameter of ToDtype

### ISSUE THREAD

**Issue by ShuaibZyx** [CharlieCrosley/Polygen-Pytorch#2]
Sorry to bother you again.
TypeError: ToDtype.__init__() got an unexpected keyword argument 'scale'
mudules.py 958:   self.transforms = v2.Compose([
            v2.ToDtype(torch.float32, scale=True)
])
The scale parameter of the ToDtype method was not present in Pytorch2.0.1. When I removed this parameter and continued to run, I got the result that the model Settings and weights were all provided by you. What went wrong? Could that be the parameter?
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/163d99fb-4b81-4513-9de1-af349d1fe485)
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/afd88c26-5a60-44bf-a037-32e227cf56fd)

**Comment by CharlieCrosley** [comment]
Apologies for the mistake, the README is outdated. The scale parameter should be present in the latest PyTorch version 2.3.0 or the nightly version. You may be able to just update the torchvision package. 
The reason not using this gives bad results is because it scales the image values that are in the range [0..255] to [0..1]. The smaller range of values makes learning more stable and faster. Since it was trained with values in the range [0..1], they must also be in that range for inference.

**Comment by ShuaibZyx** [comment]
Thank you for your quick response. After changing the Pytorch version, this method can be passed, and I get this result.
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/93c130dd-0ec0-4e28-879c-75b433264c00)
The number of vertices and faces in the model and the shape of the model look reasonable. But there are a lot of unconnected faces in the middle of the model. Is this a normal situation? Thanks again!

**Comment by CharlieCrosley** [comment]
It is expected that there will be some bad quality samples, this can be helped by reducing the "top_p" parameter when sampling the model to something like 0.1. This will restrict the predictions to only the most confident predictions at the cost of diversity. The pretrained model isn't perfect, so experimenting with images from different angles will help to find better results.

**Comment by ShuaibZyx** [comment]
Thanks for your answer, I tried to adjust the top_p parameter to sample the model and did get different results. I have a few more questions to ask, if I only use image features and not class features to reason the model, can this training be successful? Another problem is that when I feed resnet an image with a black background (pixel value is 0), it understands that I want it to extract features from parts of the image other than 0. How does this work? I am new to this area, please feel free to enlighten me. Thank you very much!

**Comment by CharlieCrosley** [comment]
Only using image input and not class labels will still train fine, from my experiments there is only a small improvement in when using class labels. 
The model learns that the black background has very little/no impact on the loss, therefore it will adjust its parameters to recognise features found on the object rather than having useless parameters that have strong responses to the black background. This happens because the gradient of the loss with respect to the parameters that only pay attention to the black background will be very close to zero to show that it has very little impact on the loss. Gradient descent will nudge these parameters in a direction that learns useful features and ignores the black background.

**Comment by ShuaibZyx** [comment]
Thank you for your detailed explanation. I think I understand the image mask better. I noticed that you updated the readme to add an instance image of the result. The results shown in the images are great, and the graphics are beautiful. I would like to learn how you make such neat and beautiful pictures? Is it a software or a website? Thank you for your help!

**Comment by CharlieCrosley** [comment]
The image of the meshes are from a blender viewport render of the wireframe. To format the final image I didn't do anything special, just made a table in Microsoft word and put an image in each cell. There are definitely better ways to do this but I haven't looked into it.

**Comment by ShuaibZyx** [comment]
Thanks for your reply, I tried to reproduce your training process, obtained vertex model and surface model and sampled them. When I look at the sampling results, I find that my face model often samples only one face, where can this problem occur? Please help me! Thank you!
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/77b0e021-69f4-4874-b749-97009bb93916)
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/f046144d-5bf2-46cb-bf9c-19c05adaa67d)
![image](https://github.com/CharlieCrosley/Polygen-Pytorch/assets/106308226/f20be233-3cdc-482d-95fd-63a2b3c3f800)

**Comment by CharlieCrosley** [comment]
I'm not sure what the cause of the problem is. The face model will predict a zero after the last face, so it is predicting a zero too early. Try to compare the inputs to the model when training and the inputs when sampling to make sure they have the same format. The problem could also be the dataset not having enough examples or poor quality examples. You may just have to experiment to find the cause.
